import React from "react";
import Head from "next/head";

import Navbar from "./Navbar/Navbar";

function MainLayout({ title = "Todo", children }) {
  return (
    <>
      <Head>
        <title>{title}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="h-auto min-h-screen max-w-6xl md:w-4/5 sm:w-full mx-auto md:py-20">
        <Navbar />
        {children}
      </div>
    </>
  );
}

export default MainLayout;
